import { requireCmsUser } from "@/lib/auth/authorization";
import { createClient } from "@/lib/supabase/server";
import { addTelegramUserAction, saveTelegramSettingsAction, toggleTelegramUserAction } from "../actions";

export const dynamic = "force-dynamic";

export default async function TelegramIntegrationPage() {
  await requireCmsUser("settings.manage");
  const supabase = await createClient();
  const [{ data: users }, { data: settings }, { data: recent }] = await Promise.all([
    supabase.from("telegram_users").select("id,telegram_user_id,display_name,role,is_active,created_at").order("created_at", { ascending: false }),
    supabase.from("site_settings").select("telegram_auto_post_enabled,telegram_notify_owner_enabled").eq("id", true).single(),
    supabase.from("telegram_actions").select("id,telegram_user_id,action,status,error_message,created_at").order("created_at", { ascending: false }).limit(20),
  ]);
  const configured = Boolean(process.env.TELEGRAM_BOT_TOKEN && process.env.TELEGRAM_WEBHOOK_SECRET && process.env.TELEGRAM_OWNER_IDS);
  return <div className="grid gap-6"><div><p className="text-sm font-bold text-primary">Telegram</p><h1 className="mt-1 text-3xl font-black">تكامل البوت</h1><p className="mt-2 text-sm text-muted-foreground">الحالة: <b>{configured ? "Configured" : "Not configured"}</b> · القناة: <b>{process.env.TELEGRAM_CHANNEL_ID ? "Configured" : "Not configured"}</b>. القيم السرية لا تظهر هنا.</p></div>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-black">السلوك</h2><form action={saveTelegramSettingsAction} className="mt-4 grid gap-3"><label className="flex items-center gap-2 text-sm font-bold"><input name="notifyOwner" type="checkbox" defaultChecked={settings?.telegram_notify_owner_enabled}/> إشعار المالك</label><label className="flex items-center gap-2 text-sm font-bold"><input name="autoPost" type="checkbox" defaultChecked={settings?.telegram_auto_post_enabled}/> النشر التلقائي إلى القناة عند تفعيل Rule مناسب</label><button className="h-10 w-fit rounded-full bg-primary px-5 text-sm font-bold text-primary-foreground">حفظ</button></form></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-black">المستخدمون المصرحون</h2><form action={addTelegramUserAction} className="mt-4 grid gap-3 md:grid-cols-4"><input name="telegramUserId" required inputMode="numeric" placeholder="Telegram numeric ID" className="h-10 rounded-xl border border-border bg-background px-3"/><input name="displayName" placeholder="الاسم" className="h-10 rounded-xl border border-border bg-background px-3"/><select name="role" className="h-10 rounded-xl border border-border bg-background px-3"><option value="editor">Editor</option><option value="admin">Admin</option><option value="owner">Owner</option></select><button className="h-10 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">إضافة/تحديث</button></form><div className="mt-5 grid gap-2">{users?.length ? users.map((user)=><div key={user.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-border p-3 text-sm"><b>{user.display_name || "بدون اسم"}</b><code dir="ltr" className="rounded bg-accent px-2 py-1">{String(user.telegram_user_id)}</code><span>{user.role}</span><span className="text-muted-foreground">{user.is_active ? "نشط" : "موقوف"}</span><form action={toggleTelegramUserAction} className="mr-auto"><input type="hidden" name="id" value={user.id}/><input type="hidden" name="active" value={String(!user.is_active)}/><button className="rounded-full border border-border px-3 py-1 text-xs font-bold">{user.is_active ? "إيقاف" : "تفعيل"}</button></form></div>) : <p className="text-sm text-muted-foreground">لا يوجد مستخدمون في جدول السماح بعد. يبقى TELEGRAM_OWNER_IDS طبقة السماح الأساسية.</p>}</div></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-black">آخر العمليات</h2><div className="mt-4 grid gap-2">{recent?.length ? recent.map((row)=><div key={row.id} className="rounded-xl border border-border p-3 text-sm"><div className="flex justify-between gap-3"><b>{row.action}</b><span>{row.status}</span></div><p className="mt-1 text-xs text-muted-foreground">User {String(row.telegram_user_id)} · {row.created_at}</p>{row.error_message ? <p className="mt-1 text-xs text-destructive">{row.error_message}</p> : null}</div>) : <p className="text-sm text-muted-foreground">لا توجد عمليات مسجلة.</p>}</div></section>
  </div>;
}
