import { createServerClient } from "@supabase/ssr";
import { NextResponse,type NextRequest } from "next/server";
import { getSupabasePublicEnv,isSupabaseConfigured } from "@/lib/supabase/env";
const REDIRECT_EXCLUDES=["/admin","/auth","/api","/preview","/_next","/robots.txt","/sitemap.xml","/feed.xml","/rss.xml","/atom.xml","/feed.json","/llms.txt"];
export async function updateSession(request:NextRequest){
 if(!isSupabaseConfigured()){if(request.nextUrl.pathname.startsWith("/admin")&&request.nextUrl.pathname!=="/admin/login"){const loginUrl=request.nextUrl.clone();loginUrl.pathname="/admin/login";loginUrl.searchParams.set("next",request.nextUrl.pathname);return NextResponse.redirect(loginUrl);}return NextResponse.next({request});}
 let response=NextResponse.next({request});const{url,publishableKey}=getSupabasePublicEnv();const supabase=createServerClient(url,publishableKey,{cookies:{getAll(){return request.cookies.getAll();},setAll(cookiesToSet,cacheHeaders){cookiesToSet.forEach(({name,value})=>request.cookies.set(name,value));response=NextResponse.next({request});cookiesToSet.forEach(({name,value,options})=>response.cookies.set(name,value,options));Object.entries(cacheHeaders).forEach(([key,value])=>response.headers.set(key,value));}}});
 const{data,error}=await supabase.auth.getClaims();const claims=error?null:data?.claims;const pathname=request.nextUrl.pathname;
 if((request.method==="GET"||request.method==="HEAD")&&!REDIRECT_EXCLUDES.some((prefix)=>pathname===prefix||pathname.startsWith(`${prefix}/`))){try{const{data:redirectRows}=await supabase.schema("blog").rpc("resolve_redirect",{p_source_path:pathname});const row=Array.isArray(redirectRows)?redirectRows[0]:null;if(row&&typeof row.destination_url==="string"&&typeof row.status_code==="number"){const destination=new URL(row.destination_url,request.url);const redirect=NextResponse.redirect(destination,row.status_code);response.cookies.getAll().forEach((cookie)=>redirect.cookies.set(cookie));return redirect;}}catch{/* A redirect lookup failure must never take the site down. */}}
 if(pathname.startsWith("/admin")&&pathname!=="/admin/login"&&!claims){const loginUrl=request.nextUrl.clone();loginUrl.pathname="/admin/login";loginUrl.searchParams.set("next",pathname);const redirect=NextResponse.redirect(loginUrl);response.cookies.getAll().forEach((cookie)=>redirect.cookies.set(cookie));return redirect;}
 if(pathname==="/admin/login"&&claims){const adminUrl=request.nextUrl.clone();adminUrl.pathname="/admin";adminUrl.search="";const redirect=NextResponse.redirect(adminUrl);response.cookies.getAll().forEach((cookie)=>redirect.cookies.set(cookie));return redirect;}
 return response;
}
