import { createClient } from "@/lib/supabase/server";
import { requireCmsUser } from "@/lib/auth/authorization";
import { emailProvider } from "@/lib/email/provider";
import { cancelNewsletterCampaignAction, createNewsletterCampaignAction, sendNewsletterCampaignAction, sendNewsletterTestAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function NewsletterAdminPage() {
  await requireCmsUser("content.publish");
  const supabase = await createClient();
  const [{ data: campaigns }, { count: activeSubscribers }, { data: settings }] = await Promise.all([
    supabase.from("newsletter_campaigns").select("id,subject,status,scheduled_at,sent_at,created_at,last_error").order("created_at", { ascending: false }).limit(30),
    supabase.from("subscribers").select("id", { count: "exact", head: true }).eq("status", "active"),
    supabase.from("site_settings").select("timezone,newsletter_sender_email").eq("id", true).single(),
  ]);
  return <div className="grid gap-6">
    <div><p className="text-sm font-bold text-primary">Newsletter</p><h1 className="mt-1 text-3xl font-black">النشرة البريدية</h1><p className="mt-2 text-sm text-muted-foreground">المشتركون النشطون: {activeSubscribers ?? 0} · المزوّد: {emailProvider.configured ? "Configured" : "Not configured"}</p></div>
    {!emailProvider.configured ? <div className="rounded-2xl border border-amber-300/60 bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">RESEND_API_KEY غير مهيأ. يمكنك إدارة الحملات والاشتراكات، لكن الإرسال الفعلي سيبقى متوقفًا بأمان.</div> : null}
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-black">حملة جديدة</h2><form action={createNewsletterCampaignAction} className="mt-4 grid gap-3"><input name="subject" required maxLength={240} placeholder="العنوان" className="h-11 rounded-xl border border-border bg-background px-3"/><input name="preheader" maxLength={500} placeholder="Preheader اختياري" className="h-11 rounded-xl border border-border bg-background px-3"/><textarea name="body" required maxLength={50000} rows={8} placeholder="محتوى الرسالة كنص آمن" className="rounded-xl border border-border bg-background p-3 leading-7"/><label className="grid gap-1 text-sm font-bold">جدولة اختيارية — {settings?.timezone || "Asia/Aden"}<input name="scheduledAt" type="datetime-local" className="h-11 rounded-xl border border-border bg-background px-3 font-normal"/></label><button className="h-11 w-fit rounded-full bg-primary px-6 text-sm font-bold text-primary-foreground">حفظ الحملة</button></form></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-xl font-black">إرسال تجريبي</h2><form action={sendNewsletterTestAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input name="to" type="email" required placeholder="البريد التجريبي" className="h-11 rounded-xl border border-border bg-background px-3"/><input name="subject" required placeholder="العنوان" className="h-11 rounded-xl border border-border bg-background px-3"/><textarea name="body" required rows={4} placeholder="النص" className="rounded-xl border border-border bg-background p-3 sm:col-span-2"/><button disabled={!emailProvider.configured || !settings?.newsletter_sender_email} className="h-11 w-fit rounded-full border border-border px-5 text-sm font-bold disabled:opacity-50">إرسال اختبار</button></form></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-5"><h2 className="text-xl font-black">الحملات</h2></div><div className="divide-y divide-border">{campaigns?.length ? campaigns.map((campaign)=><article key={campaign.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-black">{campaign.subject}</p><p className="mt-1 text-xs text-muted-foreground">{campaign.status} · {campaign.scheduled_at ? `مجدولة ${campaign.scheduled_at}` : campaign.sent_at ? `أرسلت ${campaign.sent_at}` : campaign.created_at}</p>{campaign.last_error ? <p className="mt-1 text-xs text-destructive">{campaign.last_error}</p> : null}</div><div className="flex flex-wrap gap-2">{!["sent","cancelled"].includes(campaign.status) ? <form action={sendNewsletterCampaignAction}><input type="hidden" name="id" value={campaign.id}/><button disabled={!emailProvider.configured || !settings?.newsletter_sender_email} className="rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground disabled:opacity-50">إرسال/متابعة</button></form> : null}{["draft","scheduled","failed"].includes(campaign.status) ? <form action={cancelNewsletterCampaignAction}><input type="hidden" name="id" value={campaign.id}/><button className="rounded-full border border-border px-4 py-2 text-xs font-bold">إلغاء</button></form> : null}</div></article>) : <p className="p-5 text-sm text-muted-foreground">لا توجد حملات بعد.</p>}</div></section>
  </div>;
}
