import type { Post, SiteSettings } from "@/types/content";
import { getAbsoluteUrl, getCanonicalPostUrl } from "@/lib/site/url";

export function escapeXml(value: string) { return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;"); }
function date(value?: string) { const parsed=value?new Date(value):null; return parsed && !Number.isNaN(parsed.valueOf()) ? parsed.toUTCString() : new Date(0).toUTCString(); }
export function buildRss(posts: Post[], settings: SiteSettings) {
  const items=posts.map((post)=>`<item><title>${escapeXml(post.title)}</title><link>${escapeXml(getCanonicalPostUrl(post.slug,post.canonicalUrl,settings.siteUrl))}</link><guid isPermaLink="true">${escapeXml(getCanonicalPostUrl(post.slug,post.canonicalUrl,settings.siteUrl))}</guid><description>${escapeXml(post.excerpt)}</description><pubDate>${date(post.publishedAt)}</pubDate><author>${escapeXml(post.author?.name||settings.authorName)}</author><category>${escapeXml(post.categoryName||post.category)}</category></item>`).join("");
  return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${escapeXml(settings.siteName)}</title><link>${escapeXml(settings.siteUrl)}</link><description>${escapeXml(settings.siteDescription)}</description><language>ar</language><atom:link href="${escapeXml(getAbsoluteUrl("/feed.xml",settings.siteUrl))}" rel="self" type="application/rss+xml"/>${items}</channel></rss>`;
}
export function buildAtom(posts: Post[], settings: SiteSettings) {
  const updated=posts[0]?.updatedAt||posts[0]?.publishedAt||"1970-01-01T00:00:00.000Z";
  const entries=posts.map((post)=>{const url=getCanonicalPostUrl(post.slug,post.canonicalUrl,settings.siteUrl);return `<entry><title>${escapeXml(post.title)}</title><id>${escapeXml(url)}</id><link href="${escapeXml(url)}"/><published>${new Date(post.publishedAt).toISOString()}</published><updated>${new Date(post.updatedAt||post.publishedAt).toISOString()}</updated><author><name>${escapeXml(post.author?.name||settings.authorName)}</name></author><summary>${escapeXml(post.excerpt)}</summary><category term="${escapeXml(post.category)}"/></entry>`;}).join("");
  return `<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom" xml:lang="ar"><title>${escapeXml(settings.siteName)}</title><id>${escapeXml(settings.siteUrl)}</id><link href="${escapeXml(settings.siteUrl)}"/><link rel="self" href="${escapeXml(getAbsoluteUrl("/atom.xml",settings.siteUrl))}"/><updated>${new Date(updated).toISOString()}</updated>${entries}</feed>`;
}
export function buildJsonFeed(posts: Post[], settings: SiteSettings) { return { version:"https://jsonfeed.org/version/1.1", title:settings.siteName, home_page_url:settings.siteUrl, feed_url:getAbsoluteUrl("/feed.json",settings.siteUrl), description:settings.siteDescription, language:"ar", items:posts.map((post)=>({ id:getCanonicalPostUrl(post.slug,post.canonicalUrl,settings.siteUrl), url:getCanonicalPostUrl(post.slug,post.canonicalUrl,settings.siteUrl), title:post.title, summary:post.excerpt, content_html:post.contentHtml||undefined, date_published:post.publishedAt, date_modified:post.updatedAt||post.publishedAt, authors:[{name:post.author?.name||settings.authorName}], tags:post.tags })) }; }
